# Generated by Django 4.2.2 on 2023-07-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_trackker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(default='expense', max_length=50),
            preserve_default=False,
        ),
    ]
