# Generated by Django 4.2.2 on 2023-07-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_trackker', '0002_expense_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensepayment',
            name='portion_type',
            field=models.CharField(choices=[('amount', 'Amount'), ('percentage', 'Percentage')], default='amount', max_length=10),
        ),
        migrations.AlterField(
            model_name='expensepayment',
            name='portion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter either an amount or a percentage.', max_digits=6, null=True),
        ),
    ]
