# Generated by Django 4.2.2 on 2023-07-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_trackker', '0003_expensepayment_portion_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='new_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance_trackker.category'),
        ),
    ]
