# Generated by Django 4.2.2 on 2023-07-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_trackker', '0004_expense_new_category_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='new_category',
        ),
    ]
