# Generated by Django 4.2.2 on 2023-07-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_trackker', '0006_expensepayment_calculated_portion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='portion_type',
            field=models.CharField(choices=[('amount', 'Amount'), ('percentage', 'Percentage')], default='amount', max_length=10),
        ),
    ]
