# Generated by Django 4.2.2 on 2023-07-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_trackker', '0007_expense_portion_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='users',
        ),
    ]
